import type { Metadata } from "next"
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
const AppProvidersWrapper = dynamic(() => import('@/components/AppProvidersWrapper'))

import "./globals.css"
import dynamic from 'next/dynamic'
import LeftSideBar from '@/components/LeftSideBar'
import { SidebarTrigger } from '@/components/ui/sidebar'
import RightSideBar from '@/components/RightSideBar'

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout ({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', fontHeading.variable, fontBody.variable)}>
        <AppProvidersWrapper>
          <LeftSideBar />
          {children}
          <RightSideBar />
        </AppProvidersWrapper>
      </body>
    </html>
  )
}
