import { cn } from '@/lib/utils'
import type { Metadata } from "next"
import { Inter } from 'next/font/google'
const AppProvidersWrapper = dynamic(() => import('@/components/AppProvidersWrapper'))

import Header from '@/components/Header'
import LeftSideBar from '@/components/LeftSideBar'
import RightSideBar from '@/components/RightSideBar'
import dynamic from 'next/dynamic'

import "./globals.css"

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout ({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', fontHeading.variable, fontBody.variable)}>
        <AppProvidersWrapper>
          <LeftSideBar />
          <main className='flex flex-col w-full'>
            <Header />
            <div className='container h-full'>{children}</div>
          </main>
          <RightSideBar />
        </AppProvidersWrapper>
      </body>
    </html>
  )
}
